const carsData = [
  {
    id: 1,
    brand: "Toyota",
    model: "Camry",
    year: 2022,
    price: 28000,
    images: [
      "../public/CarImages/TC/toyotaCamry(1).jpg",
      "../public/CarImages/TC/toyotaCamry(2).jpg",
      "../public/CarImages/TC/toyotaCamry(3).jpg",
      "../public/CarImages/TC/toyotaCamry(4).jpg",
      "../public/CarImages/TC/toyotaCamry(5).jpg",
    ],
    fuelType: "Petrol",
    mileage: 15000,
    transmission: "Automatic",
    engine: "2.5L",
    horsepower: 203,
    color: "White",
    condition: "Used",
    rating: 4.5,
    features: ["Bluetooth", "Backup Camera", "Lane Assist"],
  },
  {
    id: 2,
    brand: "BMW",
    model: "3 Series",
    year: 2023,
    price: 42000,
    images: [
      "../public/CarImages/BMW3/bmw1.avif",
      "../public/CarImages/BMW3/bmw2.avif",
      "../public/CarImages/BMW3/bmw3.avif",
      "../public/CarImages/BMW3/bmw4.avif",
      "../public/CarImages/BMW3/bmw5.avif",
    ],
    fuelType: "Petrol",
    mileage: 8000,
    transmission: "Automatic",
    engine: "2.0L Turbo",
    horsepower: 255,
    color: "Black",
    condition: "Used",
    rating: 4.7,
    features: ["Leather Seats", "Navigation", "Parking Sensors"],
  },
  {
    id: 3,
    brand: "Mercedes",
    model: "C-Class",
    year: 2023,
    price: 44000,
    images: [
      "../public/CarImages/MercC/merc.avif",
      "../public/CarImages/MercC/merc1.avif",
      "../public/CarImages/MercC/merc2.avif",
      "../public/CarImages/MercC/merc3.avif",
      "../public/CarImages/MercC/merc4.avif",
      "../public/CarImages/MercC/merc5.avif",
    ],
    fuelType: "Petrol",
    mileage: 6000,
    transmission: "Automatic",
    engine: "2.0L Turbo",
    horsepower: 255,
    color: "Silver",
    condition: "Used",
    rating: 4.8,
    features: ["Ambient Lighting", "Digital Dash", "Heated Seats"],
  },
  {
    id: 4,
    brand: "Audi",
    model: "A4",
    year: 2023,
    price: 41000,
    images: [
      "../public/CarImages/audiA4/audi.avif",
      "../public/CarImages/audiA4/audi1.avif",
      "../public/CarImages/audiA4/audi2.avif",
      "../public/CarImages/audiA4/audi3.avif",
      "../public/CarImages/audiA4/audi4.avif",
    ],
    fuelType: "Petrol",
    mileage: 9000,
    transmission: "Automatic",
    engine: "2.0L Turbo",
    horsepower: 261,
    color: "Gray",
    condition: "Used",
    rating: 4.6,
    features: ["Quattro AWD", "Virtual Cockpit", "Apple CarPlay"],
  },
  {
    id: 5,
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    price: 39000,
    images: [
      "../public/CarImages/tesla/tesla1.avif",
      "../public/CarImages/tesla/tesla2avif.avif",
      "../public/CarImages/tesla/tesla3.avif",
      "../public/CarImages/tesla/tesla4.avif",
      "../public/CarImages/tesla/tesla5.avif",
    ],
    fuelType: "Electric",
    mileage: 5000,
    transmission: "Automatic",
    engine: "Electric",
    horsepower: 283,
    color: "White",
    condition: "Used",
    rating: 4.9,
    features: ["Autopilot", "Touchscreen", "Glass Roof"],
  },
  {
    id: 6,
    brand: "Ford",
    model: "Mustang",
    year: 2022,
    price: 43000,
    images: [
      "../public/CarImages/mustang/ford1.avif",
      "../public/CarImages/mustang/ford2.avif",
      "../public/CarImages/mustang/ford3.avif",
      "../public/CarImages/mustang/ford4.avif",
      "../public/CarImages/mustang/ford5.avif",
    ],
    fuelType: "Petrol",
    mileage: 12000,
    transmission: "Manual",
    engine: "5.0L V8",
    horsepower: 450,
    color: "Red",
    condition: "Used",
    rating: 4.7,
    features: ["Sport Mode", "Launch Control", "Premium Audio"],
  },
  {
    id: 7,
    brand: "Chevrolet",
    model: "Camaro",
    year: 2022,
    price: 31000,
    images: [
      "../public/CarImages/chevy/chev1.avif",
      "../public/CarImages/chevy/chev2.avif",
      "../public/CarImages/chevy/chev3.avif",
      "../public/CarImages/chevy/chevy4.jpg",
      "../public/CarImages/chevy/chevy5.jpg",
    ],
    fuelType: "Petrol",
    mileage: 14000,
    transmission: "Manual",
    engine: "2.0L Turbo",
    horsepower: 275,
    color: "Yellow",
    condition: "Used",
    rating: 4.4,
    features: ["Sport Exhaust", "Rear Camera", "Keyless Entry"],
  },
  {
    id: 8,
    brand: "BMW",
    model: "M4 Competition",
    year: 2023,
    price: 78000,
    images: [
      "../public/CarImages/BMWM4/bmw.avif",
      "../public/CarImages/BMWM4/bmw1.avif",
      "../public/CarImages/BMWM4/bmw2.avif",
      "../public/CarImages/BMWM4/bmw3.avif",
      "../public/CarImages/BMWM4/bmw4.jpg",
    ],
    fuelType: "Petrol",
    mileage: 4500,
    transmission: "Automatic",
    engine: "3.0L Twin-Turbo I6",
    horsepower: 503,
    color: "Isle of Man Green",
    condition: "Used",
    rating: 4.9,
    features: ["M xDrive AWD", "Carbon Bucket Seats", "Head-Up Display"],
  },
  {
    id: 9,
    brand: "Mercedes",
    model: "AMG C63",
    year: 2022,
    price: 72000,
    images: [
      "../public/CarImages/AMG-C63/amg1.avif",
      "../public/CarImages/AMG-C63/amg2.avif",
      "../public/CarImages/AMG-C63/amg3.avif",
      "../public/CarImages/AMG-C63/amg4.avif",
      "../public/CarImages/AMG-C63/amg5.avif",
    ],
    fuelType: "Petrol",
    mileage: 11000,
    transmission: "Automatic",
    engine: "4.0L Twin-Turbo V8",
    horsepower: 503,
    color: "Matte Gray",
    condition: "Used",
    rating: 4.8,
    features: ["AMG Ride Control", "Burmester Sound", "Track Pace App"],
  },
  {
    id: 10,
    brand: "Porsche",
    model: "911 Carrera S",
    year: 2023,
    price: 125000,
    images: [
      "../public/CarImages/PorscheCarrera/car1.avif",
      "../public/CarImages/PorscheCarrera/car2.avif",
      "../public/CarImages/PorscheCarrera/car3.avif",
      "../public/CarImages/PorscheCarrera/car4.avif",
      "../public/CarImages/PorscheCarrera/car5.avif",
    ],
    fuelType: "Petrol",
    mileage: 3200,
    transmission: "Automatic",
    engine: "3.0L Twin-Turbo Flat-6",
    horsepower: 443,
    color: "Chalk",
    condition: "Used",
    rating: 5.0,
    features: ["PASM Suspension", "Sport Chrono Package", "Bose Audio"],
  },
  {
    id: 11,
    brand: "Ford",
    model: "Explorer ST",
    year: 2023,
    price: 54000,
    images: [
      "../public/CarImages/Explorer/94b83070-8561-4057-ad87-7d820c6b726a.avif",
      "../public/CarImages/Explorer/0f0f03c8-cdf6-44ba-b112-cd52790ec140.avif",
      "../public/CarImages/Explorer/9ec0db06-9240-43b8-af0d-bbb706ccf8c2.avif",
      "../public/CarImages/Explorer/564f7b0f-ccbd-44a1-b500-62904f162139.avif",
      "../public/CarImages/Explorer/e88badb0-311e-494d-a9fa-8d37cae09608.avif",
    ],
    fuelType: "Petrol",
    mileage: 9500,
    transmission: "Automatic",
    engine: "3.0L EcoBoost V6",
    horsepower: 400,
    color: "Rapid Red",
    condition: "Used",
    rating: 4.6,
    features: ["Terrain Management", "Massaging Seats", "Co-Pilot360"],
  },
  {
    id: 12,
    brand: "Nissan",
    model: "Z Performance",
    year: 2023,
    price: 51000,
    images: [
      "../public/CarImages/zPerformance/4b5f69c6-df87-4c88-8521-ed8c7196fd86.avif",
      "../public/CarImages/zPerformance/1ac54eb7-5bbc-4dba-97f2-53d7f0fa4562.avif",
      "../public/CarImages/zPerformance/29e924c0-52db-4b7b-bbc0-7c72e7774571.avif",
      "../public/CarImages/zPerformance/b8ab0ff5-d9d2-4c77-af2b-fa0dbeb0715b.avif",
      "../public/CarImages/zPerformance/e3f6623d-46d4-4019-9d21-877ab7b1f3fa.avif",
    ],
    fuelType: "Petrol",
    mileage: 2800,
    transmission: "Manual",
    engine: "3.0L Twin-Turbo V6",
    horsepower: 400,
    color: "Ikazuchi Yellow",
    condition: "Used",
    rating: 4.7,
    features: ["Rays Wheels", "LSD Differential", "Launch Control"],
  },
  {
    id: 13,
    brand: "Audi",
    model: "RS5 Coupe",
    year: 2023,
    price: 79000,
    images: [
      "../public/CarImages/RS5Coupe/2027-audi-rs5-pr113-69972202512a6.avif",
      "../public/CarImages/RS5Coupe/2027-audi-rs5-interior-pr101-6997240089ae5.avif",
      "../public/CarImages/RS5Coupe/2027-audi-rs5-interior-pr102-699724007fbcb.avif",
      "../public/CarImages/RS5Coupe/2027-audi-rs5-pr110-699721ffc4fc.avif",
      "../public/CarImages/RS5Coupe/2027-audi-rs5-pr112-69972201a888a.avif",
    ],
    fuelType: "Petrol",
    mileage: 5200,
    transmission: "Automatic",
    engine: "2.9L Twin-Turbo V6",
    horsepower: 444,
    color: "Nardo Gray",
    condition: "Used",
    rating: 4.8,
    features: ["Quattro Sport Differential", "Dynamic Ride", "Matrix LED"],
  },
  {
    id: 14,
    brand: "Porsche",
    model: "Macan GTS",
    year: 2022,
    price: 82000,
    images: [
      "../public/CarImages/MacanGTS/2026-porsche-macan-gts-ev-102-698b52a40c7e0.avif",
      "../public/CarImages/MacanGTS/2026-porsche-macan-gts-ev-116-698b52aedc2b6.avif",
      "../public/CarImages/MacanGTS/2026-porsche-macan-gts-ev-129-698b52b87adb6.avif",
      "../public/CarImages/MacanGTS/2026-porsche-macan-gts-ev-130-698b54d3e2dfb.avif",
      "../public/CarImages/MacanGTS/2026-porsche-macan-gts-ev-134-698b54d867695.avif",
    ],
    fuelType: "Petrol",
    mileage: 14000,
    transmission: "Automatic",
    engine: "2.9L Twin-Turbo V6",
    horsepower: 434,
    color: "Python Green",
    condition: "Used",
    rating: 4.9,
    features: ["Air Suspension", "Sport Exhaust", "Carbon Interior Package"],
  },
  {
    id: 15,
    brand: "Nissan",
    model: "GT-R Nismo",
    year: 2022,
    price: 215000,
    images: [
      "../public/CarImages/GTR/2017-Nissan-GT-R-102.avif",
      "../public/CarImages/GTR/2017-Nissan-GT-R-104.avif",
      "../public/CarImages/GTR/2017-Nissan-GT-R-116.avif",
      "../public/CarImages/GTR/2017-Nissan-GT-R-122.avif",
      "../public/CarImages/GTR/2017-Nissan-GT-R-124.avif",
    ],
    fuelType: "Petrol",
    mileage: 1800,
    transmission: "Automatic",
    engine: "3.8L Twin-Turbo V6",
    horsepower: 600,
    color: "Solid White",
    condition: "Used",
    rating: 5.0,
    features: ["Nismo Carbon Aero", "Brembo Carbon Ceramics", "Alcantara Trim"],
  },
  {
    id: 16,
    brand: "BMW",
    model: "X5 M Competition",
    year: 2023,
    price: 112000,
    images: [
      "../public/CarImages/X5/2025-bmw-x5-m-competition-107-698e1ad5296c0.avif",
      "../public/CarImages/X5/2025-bmw-x5-m-competition-107-698e178d0a55f.avif",
      "../public/CarImages/X5/2025-bmw-x5-m-competition-108-698e1ad5165ad.avif",
      "../public/CarImages/X5/2025-bmw-x5-m-competition-110-698e1adbcb772.avif",
      "../public/CarImages/X5/2025-bmw-x5-m-competition-121-698e179eaf21c.avif",
    ],
    fuelType: "Petrol",
    mileage: 6100,
    transmission: "Automatic",
    engine: "4.4L Twin-Turbo V8",
    horsepower: 617,
    color: "Marina Bay Blue",
    condition: "Used",
    rating: 4.8,
    features: ["M xDrive", "Executive Package", "Sky Lounge Roof"],
  },
  {
    id: 17,
    brand: "Mercedes",
    model: "E450 Coupe",
    year: 2023,
    price: 68000,
    images: [
      "../public/CarImages/E450/2025-mercedes-benz-e450-all-terrain-108-68e681973864e.avif",
      "../public/CarImages/E450/2025-mercedes-benz-e450-all-terrain-122-68e6819dcd6b7.avif",
      "../public/CarImages/E450/2025-mercedes-benz-e450-all-terrain-128-68e681974284d.avif",
      "../public/CarImages/E450/2025-mercedes-benz-e450-all-terrain-353-68e6805ed2370.avif",
      "../public/CarImages/E450/2025-mercedes-benz-e450-all-terrain-506-68e680654a51f.avif",
    ],
    fuelType: "Mild Hybrid",
    mileage: 7200,
    transmission: "Automatic",
    engine: "3.0L Turbo I6",
    horsepower: 362,
    color: "Obsidian Black",
    condition: "Used",
    rating: 4.7,
    features: ["Air Body Control", "B pillar-less Design", "Heated Armrests"],
  },
  {
    id: 18,
    brand: "Ford",
    model: "F-150 Raptor",
    year: 2023,
    price: 85000,
    images: [
      "../public/CarImages/Raptor/2024-ford-f-150-raptor-r-202-66feede751693.avif",
      "../public/CarImages/Raptor/2024-ford-f-150-raptor-r-212-66feede9be2b9.avif",
      "../public/CarImages/Raptor/2024-ford-f-150-raptor-r-222-66feede6dbcc6.avif",
      "../public/CarImages/Raptor/2024-ford-f150-raptor-r-102-66461c37f1cae.avif",
      "../public/CarImages/Raptor/2024-ford-f150-raptor-r-103-66461c35240f7.avif",
    ],
    fuelType: "Petrol",
    mileage: 10500,
    transmission: "Automatic",
    engine: "3.5L Twin-Turbo V6",
    horsepower: 450,
    color: "Code Orange",
    condition: "Used",
    rating: 4.9,
    features: ["Fox Live Valve Shocks", "37-inch Tires", "Trail Control"],
  },
  {
    id: 19,
    brand: "Audi",
    model: "e-tron GT",
    year: 2023,
    price: 89000,
    images: [
      "../public/CarImages/E-Tron/2025-audi-rs-e-tron-gt-performance-116-67eaaed7e6b0b.avif",
      "../public/CarImages/E-Tron/2025-audi-rs-e-tron-gt-performance-124-689b43c9c0866.avif",
      "../public/CarImages/E-Tron/2025-audi-rs-e-tron-gt-performance-128-689b4101a91f8.avif",
      "../public/CarImages/E-Tron/2025-audi-rs-e-tron-gt-performance-139-689b410e601ce.avif",
      "../public/CarImages/E-Tron/2025-audi-rs-e-tron-gt-performance-153-689b43d456017.avif",
    ],
    fuelType: "Electric",
    mileage: 4100,
    transmission: "Automatic",
    engine: "Dual Electric Motor",
    horsepower: 522,
    color: "Tactical Green",
    condition: "Used",
    rating: 4.7,
    features: ["e-quattro AWD", "Bang & Olufsen 3D", "Matrix Laser Headlights"],
  },
  {
    id: 20,
    brand: "Porsche",
    model: "Taycan 4S",
    year: 2023,
    price: 104000,
    images: [
      "../public/CarImages/Taycan/2025-porsche-taycan-4s-102-68765ba7051b9.avif",
      "../public/CarImages/Taycan/2025-porsche-taycan-4s-108-6862bce116e06.avif",
      "../public/CarImages/Taycan/2025-porsche-taycan-4s-128-6862bbb5babf9.avif",
      "../public/CarImages/Taycan/2025-porsche-taycan-4s-136-6862bceceded1.avif",
      "../public/CarImages/Taycan/2025-porsche-taycan-4s-141-6862bced58965.avif",
    ],
    fuelType: "Electric",
    mileage: 5300,
    transmission: "Automatic",
    engine: "Dual Electric Motor",
    horsepower: 522,
    color: "Frozen Blue",
    condition: "Used",
    rating: 4.8,
    features: [
      "Performance Battery Plus",
      "Rear Axle Steering",
      "Passenger Display",
    ],
  },
];

export default carsData;
